### ISSUE TITLE
suggest to default to $ssh_client

### ISSUE THREAD

**Issue by dragonxlwang** [ayzenquwe/tmux-ping#1]
tmux options does not always set, might want to fallback to $SSH_CLIENT

https://github.com/ayzenquwe/tmux-ping/blob/264d35f09c0429bb6706c65572ded98937e1b54c/scripts/ping_status.sh#L9

**Comment by ayzenquwe** [comment]
Hi! Not sure I understand the problem. Can you please elaborate on when tmux options aren't set?

**Comment by dragonxlwang** [comment]
Looks like the .sh is getting the `from` ip as 

```local ping_host="$(get_tmux_option "$ping_host_string" "$ping_host_default")"```

But it doesn't work at least for my case when I connect through ssh/mosh to a box and in tmux: 

```tmux show-option -gqv "@ping_host``` 

returns nothing.

So I was thinking to make it fallback to check with ssh if [[ -z ping_host  ]]

**Comment by ayzenquwe** [comment]
As far as I remember this get_tmux_option thing was to allow people to configure a host to ping. So you can set ping_host option in your tmux config and the script will use it for pinging; if you don't specify this option, the default one will be used: 8.8.8.8

So if you didn't specify ping_host, the command
`tmux show-option -gqv "@ping_host`
shouldn't return a value.

Maybe 8.8.8.8 is blocked on that machine?

P.S. Let me know if I missed something. I've implemented this plugin 3 years ago and don't remember everything. :)

**Comment by dragonxlwang** [comment]
aha, just figure out that it's using 8.8.8.8 to test ping. I was thinking to test ping in a ssh session from local to remote, but not from local to DNS. 

Yes for my case, my box is blocked to ping 8.8.8.8 :)
