### ISSUE TITLE
N/A status

### ISSUE THREAD

**Issue by afreisinger** [ayzenquwe/tmux-ping#2]
Hi ! 
I don't understand what's going on. I get N/A status every time. The process is running. The output tail -f /tmp/tmux_ping_result is always -1 and what catches my attention is tail -f /tmp/tmux_ping.log always empty. I don't understand what could be happening. I am running tmux on Darwin system. Any ideas ?
Thanks

**Comment by ayzenquwe** [comment]
Hi, 

Thanks for reporting the issue. I'm currently in the process of relocation, so I don't have enough time to analyze the problem. But hopefully, I'll have some time during the weekend.

**Comment by afreisinger** [comment]
Thank you. I'll tell you if I ping from the cli and write to the file, it works...@

**Comment by ayzenquwe** [comment]
Hey,

It's quite hard to tell why it doesn't work on your system, but if you have some time, we can try to debug the problem.

First, clone the repo and add some additional logging to the `main` function and probably to the `execute_ping` function. Something like that, just to understand where it fails:
```
if ping_not_running; then
    echo "ping is not running"
    ....
```

Also, just before the ping command you can add this:
echo "ping $number_pings_flag $ping_count $timeout_flag $ping_wait_time $ping_host > $ping_log_file &"

Then, run the script and see what happens: `./ping_status.sh`
Try to run it multiple times. 

Copy-paste the outputs here.

**Comment by ayzenquwe** [comment]
By the way, what value have you set for `status-interval` in tmux config?

**Comment by afreisinger** [comment]
> Hey,
> 
> It's quite hard to tell why it doesn't work on your system, but if you have some time, we can try to debug the problem.
> 
> First, clone the repo and add some additional logging to the `main` function and probably to the `execute_ping` function. Something like that, just to understand where it fails:
> 
> ```
> if ping_not_running; then
>     echo "ping is not running"
>     ....
> ```
> 
> Also, just before the ping command you can add this: echo "ping $number_pings_flag $ping_count $timeout_flag $ping_wait_time $ping_host > $ping_log_file &"
> 
> Then, run the script and see what happens: `./ping_status.sh` Try to run it multiple times.
> 
> Copy-paste the outputs here.

```
tmux-ping/scripts on  master [!]
➜ ./ping_status.sh
ping is not running
ping -c 3 -t 10 8.8.8.8 > /tmp/tmux_ping.log &
#[fg=red]N/A

tmux-ping/scripts on  master [!]
➜ ./ping_status.sh
ping is not running
ping -c 3 -t 10 8.8.8.8 > /tmp/tmux_ping.log &
#[fg=green] 24

tmux-ping/scripts on  master [!]
➜ ./ping_status.sh
#[fg=green] 24

```

In this case the status bar change from N/A to round-trip time value, this work fine.

**Comment by afreisinger** [comment]
> By the way, what value have you set for `status-interval` in tmux config?

 ``` 
➜ tmux show-options -g | grep status-interval
status-interval 1
 ```

**Comment by ayzenquwe** [comment]
Hey Adrián,

Sorry, I completely forgot about the problem. :'(
Are you still experiencing the problem? It would be great if you could give it another try - I'll try to support you if you have the same problem.

**Comment by ayzenquwe** [comment]
I'm closing the issue. Reopen it if you encounter the problem again.
