### ISSUE TITLE
Disable colorization

### ISSUE THREAD

**Issue by molchalin** [ayzenquwe/tmux-ping#3]
Hi! Thank you for this plugin! Works great to me.

Would it be possible, to make colorization of the ping value optional?

**Comment by ayzenquwe** [comment]
Hey,

I've just added `@ping_colorize` option. To disable colors add this to your `.tmux.conf` file:
```set -g @ping_colorize false```

Out of curiosity, why do you want to disable colors?

**Comment by molchalin** [comment]
Thanks a lot!
I just like to keep my tmux monochrome

**Comment by ayzenquwe** [comment]
Understood, thanks!
